version: "3.8"

services:
  app:
    image: fastapi-todo-app:latest
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/code # Mount the source code to the container
    command:
      [
        "sh",
        "-c",
        "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8080",
      ]

  db:
    image: postgres:13
    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
